-- Stress test 2026-09-17: row policies evaluated per row what could be asked
-- once per query. Rewritten to equivalent set forms:
--   is_guardian_of(col)          -> col IN (the caller's children)
--   is_couple_participant/member -> col IN (the caller's couples)
--   EXISTS users coach-of / accepted coach_requests (correlated, per row)
--                                -> col IN (the caller's students)
--   current_coach_studio_id()    -> evaluated once
--   guardian_can_read_class_input / guardian_can_see_user
--                                -> skipped unless the caller is a guardian
-- The subqueries read guardians / couples / users / coach_requests under their
-- own policies, which let the caller see exactly the rows these ask for, so the
-- rules are unchanged. Not rewritten where a policy would read its own table.
-- Verified before applying, per table in rolled-back transactions: 11 callers
-- (coaches, a child, a guardian, a couple dancer, students, the trainer, anon)
-- x rows visible / updatable / deletable / inserts passing — 616 checks
-- identical; the same check flags deliberately broken policies.

alter policy "attendance_responses_select" on public.attendance_responses using (((EXISTS ( SELECT 1
   FROM class_inputs ci
  WHERE ((ci.id = attendance_responses.class_input_id) AND (ci.user_id = ( SELECT auth.uid() AS uid))))) OR (student_id IN ( SELECT g.child_id FROM guardians g WHERE (g.guardian_id = ( SELECT auth.uid() AS uid)))) OR (student_id = ( SELECT auth.uid() AS uid))));
alter policy "class_input_students_select" on public.class_input_students using (((EXISTS ( SELECT 1
   FROM class_inputs ci
  WHERE ((ci.id = class_input_students.class_input_id) AND (ci.user_id = ( SELECT auth.uid() AS uid))))) OR (student_id = ( SELECT auth.uid() AS uid)) OR (student_id IN ( SELECT g.child_id FROM guardians g WHERE (g.guardian_id = ( SELECT auth.uid() AS uid))))));
alter policy "class_inputs_select" on public.class_inputs using ((((couple_id IS NOT NULL) AND (couple_id IN ( SELECT c.id FROM couples c WHERE (( SELECT auth.uid() AS uid) = ANY (ARRAY[c.user_a_id, c.user_b_id, c.latin_couple_coach_id, c.ballroom_couple_coach_id]))))) OR (( SELECT (EXISTS ( SELECT 1 FROM guardians g WHERE (g.guardian_id = ( SELECT auth.uid() AS uid)))) AS is_guardian) AND guardian_can_read_class_input(id)) OR ((user_id = ( SELECT auth.uid() AS uid)) OR (student_id = ( SELECT auth.uid() AS uid)) OR ((class_inputs.user_id IN ( SELECT u.id FROM users u WHERE ((u.latin_coach_id = ( SELECT auth.uid() AS uid)) OR (u.ballroom_coach_id = ( SELECT auth.uid() AS uid)))))) OR (EXISTS ( SELECT 1
   FROM users u
  WHERE ((u.id = ( SELECT auth.uid() AS uid)) AND ((u.latin_coach_id = class_inputs.user_id) OR (u.ballroom_coach_id = class_inputs.user_id)) AND ((class_inputs.student_id = ( SELECT auth.uid() AS uid)) OR (class_inputs.student_id IS NULL)))))) OR (( SELECT auth.uid() AS uid) = user_id) OR ((( SELECT auth.jwt() AS jwt) ->> 'email'::text) = 'loic@danceuniteduk.com'::text) OR (user_id IN ( SELECT coach_requests.student_id
   FROM coach_requests
  WHERE ((coach_requests.coach_id = ( SELECT auth.uid() AS uid)) AND (coach_requests.status = 'accepted'::text))))));
alter policy "coach_requests_select" on public.coach_requests using (((student_id IN ( SELECT g.child_id FROM guardians g WHERE (g.guardian_id = ( SELECT auth.uid() AS uid)))) OR ((student_id = ( SELECT auth.uid() AS uid)) OR (coach_id = ( SELECT auth.uid() AS uid))) OR ((( SELECT auth.jwt() AS jwt) ->> 'email'::text) = 'loic@danceuniteduk.com'::text)));
alter policy "ccr_delete" on public.couple_coach_requests using (((coach_id = ( SELECT auth.uid() AS uid)) OR (couple_id IN ( SELECT c.id FROM couples c WHERE (( SELECT auth.uid() AS uid) = ANY (ARRAY[c.user_a_id, c.user_b_id]))))));
alter policy "ccr_insert" on public.couple_coach_requests with check (((couple_id IN ( SELECT c.id FROM couples c WHERE (( SELECT auth.uid() AS uid) = ANY (ARRAY[c.user_a_id, c.user_b_id])))) AND (status = 'pending'::text) AND is_coach(coach_id)));
alter policy "ccr_select" on public.couple_coach_requests using (((coach_id = ( SELECT auth.uid() AS uid)) OR (couple_id IN ( SELECT c.id FROM couples c WHERE (( SELECT auth.uid() AS uid) = ANY (ARRAY[c.user_a_id, c.user_b_id]))))));
alter policy "couple_focus_locks_select" on public.couple_focus_locks using ((is_guardian_of_couple(couple_id) OR (couple_id IN ( SELECT c.id FROM couples c WHERE (( SELECT auth.uid() AS uid) = ANY (ARRAY[c.user_a_id, c.user_b_id, c.latin_couple_coach_id, c.ballroom_couple_coach_id]))))));
alter policy "couple_focus_points_select" on public.couple_focus_points using ((is_guardian_of_couple(couple_id) OR (couple_id IN ( SELECT c.id FROM couples c WHERE (( SELECT auth.uid() AS uid) = ANY (ARRAY[c.user_a_id, c.user_b_id, c.latin_couple_coach_id, c.ballroom_couple_coach_id]))))));
alter policy "couple_practice_logs_insert" on public.couple_practice_logs with check ((couple_id IN ( SELECT c.id FROM couples c WHERE (( SELECT auth.uid() AS uid) = ANY (ARRAY[c.user_a_id, c.user_b_id])))));
alter policy "couple_practice_logs_select" on public.couple_practice_logs using ((is_guardian_of_couple(couple_id) OR (couple_id IN ( SELECT c.id FROM couples c WHERE (( SELECT auth.uid() AS uid) = ANY (ARRAY[c.user_a_id, c.user_b_id, c.latin_couple_coach_id, c.ballroom_couple_coach_id]))))));
alter policy "couple_requests_select" on public.couple_requests using (((requester_id IN ( SELECT g.child_id FROM guardians g WHERE (g.guardian_id = ( SELECT auth.uid() AS uid)))) OR (target_id IN ( SELECT g.child_id FROM guardians g WHERE (g.guardian_id = ( SELECT auth.uid() AS uid)))) OR ((requester_id = ( SELECT auth.uid() AS uid)) OR (target_id = ( SELECT auth.uid() AS uid)))));
alter policy "couples_select" on public.couples using (((user_a_id IN ( SELECT g.child_id FROM guardians g WHERE (g.guardian_id = ( SELECT auth.uid() AS uid)))) OR (user_b_id IN ( SELECT g.child_id FROM guardians g WHERE (g.guardian_id = ( SELECT auth.uid() AS uid)))) OR ((( SELECT auth.uid() AS uid) = user_a_id) OR (( SELECT auth.uid() AS uid) = user_b_id) OR (( SELECT auth.uid() AS uid) = latin_couple_coach_id) OR (( SELECT auth.uid() AS uid) = ballroom_couple_coach_id))));
alter policy "focus_points_insert" on public.focus_points with check (((user_id IN ( SELECT g.child_id FROM guardians g WHERE (g.guardian_id = ( SELECT auth.uid() AS uid)))) OR (( SELECT auth.uid() AS uid) = user_id)));
alter policy "focus_points_select" on public.focus_points using (((user_id IN ( SELECT coach_requests.student_id
   FROM coach_requests
  WHERE ((coach_requests.coach_id = ( SELECT auth.uid() AS uid)) AND (coach_requests.status = 'accepted'::text)))) OR (user_id IN ( SELECT g.child_id FROM guardians g WHERE (g.guardian_id = ( SELECT auth.uid() AS uid)))) OR ((user_id = ( SELECT auth.uid() AS uid)) OR ((focus_points.user_id IN ( SELECT u.id FROM users u WHERE ((u.latin_coach_id = ( SELECT auth.uid() AS uid)) OR (u.ballroom_coach_id = ( SELECT auth.uid() AS uid)))))) OR ((focus_points.user_id IN ( SELECT cr.student_id FROM coach_requests cr WHERE ((cr.coach_id = ( SELECT auth.uid() AS uid)) AND (cr.status = 'accepted'::text)))))) OR (( SELECT auth.uid() AS uid) = user_id) OR ((( SELECT auth.jwt() AS jwt) ->> 'email'::text) = 'loic@danceuniteduk.com'::text)));
alter policy "focus_points_update" on public.focus_points using (((user_id IN ( SELECT coach_requests.student_id
   FROM coach_requests
  WHERE ((coach_requests.coach_id = ( SELECT auth.uid() AS uid)) AND (coach_requests.status = 'accepted'::text)))) OR (user_id IN ( SELECT g.child_id FROM guardians g WHERE (g.guardian_id = ( SELECT auth.uid() AS uid)))) OR (( SELECT auth.uid() AS uid) = user_id))) with check (((user_id IN ( SELECT coach_requests.student_id
   FROM coach_requests
  WHERE ((coach_requests.coach_id = ( SELECT auth.uid() AS uid)) AND (coach_requests.status = 'accepted'::text)))) OR (user_id IN ( SELECT g.child_id FROM guardians g WHERE (g.guardian_id = ( SELECT auth.uid() AS uid)))) OR (( SELECT auth.uid() AS uid) = user_id)));
alter policy "merge_requests_select" on public.merge_requests using (((( SELECT auth.uid() AS uid) = student_id) OR (((merge_requests.student_id IN ( SELECT u.id FROM users u WHERE ((u.latin_coach_id = ( SELECT auth.uid() AS uid)) OR (u.ballroom_coach_id = ( SELECT auth.uid() AS uid)))))) OR ((merge_requests.student_id IN ( SELECT cr.student_id FROM coach_requests cr WHERE ((cr.coach_id = ( SELECT auth.uid() AS uid)) AND (cr.status = 'accepted'::text))))))));
alter policy "merge_requests_update" on public.merge_requests using ((((merge_requests.student_id IN ( SELECT u.id FROM users u WHERE ((u.latin_coach_id = ( SELECT auth.uid() AS uid)) OR (u.ballroom_coach_id = ( SELECT auth.uid() AS uid)))))) OR ((merge_requests.student_id IN ( SELECT cr.student_id FROM coach_requests cr WHERE ((cr.coach_id = ( SELECT auth.uid() AS uid)) AND (cr.status = 'accepted'::text))))))) with check ((((merge_requests.student_id IN ( SELECT u.id FROM users u WHERE ((u.latin_coach_id = ( SELECT auth.uid() AS uid)) OR (u.ballroom_coach_id = ( SELECT auth.uid() AS uid)))))) OR ((merge_requests.student_id IN ( SELECT cr.student_id FROM coach_requests cr WHERE ((cr.coach_id = ( SELECT auth.uid() AS uid)) AND (cr.status = 'accepted'::text)))))));
alter policy "practice_logs_delete" on public.practice_logs using (((( SELECT auth.uid() AS uid) = student_id) OR (student_id IN ( SELECT g.child_id FROM guardians g WHERE (g.guardian_id = ( SELECT auth.uid() AS uid))))));
alter policy "practice_logs_insert" on public.practice_logs with check (((( SELECT auth.uid() AS uid) = student_id) OR (student_id IN ( SELECT g.child_id FROM guardians g WHERE (g.guardian_id = ( SELECT auth.uid() AS uid))))));
alter policy "practice_logs_select" on public.practice_logs using (((( SELECT auth.uid() AS uid) = student_id) OR (((practice_logs.student_id IN ( SELECT u.id FROM users u WHERE ((u.latin_coach_id = ( SELECT auth.uid() AS uid)) OR (u.ballroom_coach_id = ( SELECT auth.uid() AS uid)))))) OR ((practice_logs.student_id IN ( SELECT cr.student_id FROM coach_requests cr WHERE ((cr.coach_id = ( SELECT auth.uid() AS uid)) AND (cr.status = 'accepted'::text)))))) OR (student_id IN ( SELECT g.child_id FROM guardians g WHERE (g.guardian_id = ( SELECT auth.uid() AS uid))))));
alter policy "practice_logs_update" on public.practice_logs using (((( SELECT auth.uid() AS uid) = student_id) OR (student_id IN ( SELECT g.child_id FROM guardians g WHERE (g.guardian_id = ( SELECT auth.uid() AS uid)))))) with check (((( SELECT auth.uid() AS uid) = student_id) OR (student_id IN ( SELECT g.child_id FROM guardians g WHERE (g.guardian_id = ( SELECT auth.uid() AS uid))))));
alter policy "users_select" on public.users using ((((studio_id IS NOT NULL) AND (studio_id = ( SELECT current_coach_studio_id() AS current_coach_studio_id))) OR (id IN ( SELECT coach_requests.student_id
   FROM coach_requests
  WHERE (coach_requests.coach_id = ( SELECT auth.uid() AS uid)))) OR ((EXISTS ( SELECT 1
   FROM couples c
  WHERE (((users.id = c.user_a_id) OR (users.id = c.user_b_id)) AND ((( SELECT auth.uid() AS uid) = c.user_a_id) OR (( SELECT auth.uid() AS uid) = c.user_b_id) OR (( SELECT auth.uid() AS uid) = c.latin_couple_coach_id) OR (( SELECT auth.uid() AS uid) = c.ballroom_couple_coach_id))))) OR (EXISTS ( SELECT 1
   FROM couple_requests r
  WHERE (((r.requester_id = ( SELECT auth.uid() AS uid)) AND (r.target_id = users.id)) OR ((r.target_id = ( SELECT auth.uid() AS uid)) AND (r.requester_id = users.id)))))) OR (id IN ( SELECT g.child_id FROM guardians g WHERE (g.guardian_id = ( SELECT auth.uid() AS uid)))) OR (( SELECT (EXISTS ( SELECT 1 FROM guardians g WHERE (g.guardian_id = ( SELECT auth.uid() AS uid)))) AS is_guardian) AND guardian_can_see_user(id)) OR ((invite_code IS NOT NULL) AND (role = 'coach'::text)) OR ((id = ( SELECT auth.uid() AS uid)) OR (latin_coach_id = ( SELECT auth.uid() AS uid)) OR (ballroom_coach_id = ( SELECT auth.uid() AS uid)) OR ((users.id IN ( SELECT cr.student_id FROM coach_requests cr WHERE ((cr.coach_id = ( SELECT auth.uid() AS uid)) AND (cr.status = 'accepted'::text)))))) OR (( SELECT auth.uid() AS uid) = id) OR (id = ( SELECT auth.uid() AS uid)) OR is_my_coach(id) OR ((( SELECT auth.jwt() AS jwt) ->> 'email'::text) = 'loic@danceuniteduk.com'::text)));
alter policy "users_update" on public.users using (((id IN ( SELECT g.child_id FROM guardians g WHERE (g.guardian_id = ( SELECT auth.uid() AS uid)))) OR (id = ( SELECT auth.uid() AS uid)) OR (( SELECT auth.uid() AS uid) = id))) with check (((id IN ( SELECT g.child_id FROM guardians g WHERE (g.guardian_id = ( SELECT auth.uid() AS uid)))) OR (id = ( SELECT auth.uid() AS uid)) OR (( SELECT auth.uid() AS uid) = id)));
